site_name: Arrikto Academy
site_url: https://arrikto-academy.github.io/courses

repo_name: arrikto-academy/courses
repo_url: https://github.com/arrikto-academy/courses
edit_uri: ""

theme:
  name: material
  logo: assets/arrikto-mark-white-900px.png
  palette: 
    primary: black
    accent: indigo
  features:
#    - content.tabs.link
    - navigation.tabs
    - navigation.sections
#    - navigation.top

markdown_extensions:
  - attr_list
  - admonition


nav:
  - Home: index.md
  - Modules:
    - Deploy Kubeflow:
      - Deploy MiniKF on GCP: modules/getting-started/minikf-gcp.md
    - Notebook Servers:
      - Deploy a Notebook Server: modules/notebook-servers/notebook-server-base-image.md
    - Machine Learning Pipelines:
      - Transform a Jupyter Notebook into a Kubeflow Pipeline: 
        - Introduction: modules/pipelines/notebook-to-pipeline/introduction.md
        - Notebook Walkthrough: modules/pipelines/notebook-to-pipeline/working-example.md
        - Pipeline Step Fundamentals:
          - Single-Cell Pipeline Steps: modules/pipelines/notebook-to-pipeline/step-fundamentals/single-cell.md
          - Multi-Cell Pipeline Steps: modules/pipelines/notebook-to-pipeline/step-fundamentals/multi-cell.md
          - Pipeline Step Dependencies: modules/pipelines/notebook-to-pipeline/step-fundamentals/dependencies.md
        - Working with Imports:
          - Organize Imports Together: modules/pipelines/notebook-to-pipeline/imports-fundamentals/why-organize-imports.md
          - Example: modules/pipelines/notebook-to-pipeline/imports-fundamentals/example.md
        - 'Lab: Organize Modeling Imports': modules/pipelines/notebook-to-pipeline/lab-imports.md 

