site_name: Arrikto Academy
site_url: https://arrikto-academy.github.io/learn-kubeflow

repo_name: arrikto-academy/courses
repo_url: https://github.com/arrikto-academy/learn-kubeflow
edit_uri: ""

theme:
  name: material
  logo: assets/arrikto-mark-white-900px.png
  palette: 
    primary: black
    accent: indigo
  features:
#    - content.tabs.link
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
#    - navigation.top

markdown_extensions:
  - attr_list
  - admonition


nav:
  - Home: index.md
  - Kale 101:
      - Home: modules/notebook-to-pipeline/index.md
      - Introduction:
        - Course Overview: modules/notebook-to-pipeline/introduction.md
        - Notebook Walkthrough: modules/notebook-to-pipeline/working-example.md
        - Deploy MiniKF on GCP: modules/deploy/minikf-gcp.md
        - Deploy a Notebook Server: modules/notebook-servers/notebook-server-base-image.md
      - Pipeline Step Fundamentals:
        - Single-Cell Pipeline Steps: modules/notebook-to-pipeline/step-fundamentals/single-cell.md
        - Multi-Cell Pipeline Steps: modules/notebook-to-pipeline/step-fundamentals/multi-cell.md
        - Pipeline Step Dependencies: modules/notebook-to-pipeline/step-fundamentals/dependencies.md
      - Working with Imports:
        - Gather Imports in One Cell: modules/notebook-to-pipeline/imports-fundamentals/why-organize-imports.md
        - Apply the Imports Annotation: modules/notebook-to-pipeline/imports-fundamentals/example.md
        - 'Lab: Organize Modeling Imports': modules/notebook-to-pipeline/lab-imports.md 
      - Excluding Cells from Pipelines: 
        - Skip Cells Not Used in a Step: modules/notebook-to-pipeline/exclude/skip-cells.md
        - 'Lab: Skip Cells': modules/notebook-to-pipeline/exclude/lab-skip-cells.md
        - Skip Sections Not Used: modules/notebook-to-pipeline/exclude/skip-sections.md
        - 'Lab: Skip Section': modules/notebook-to-pipeline/exclude/lab-skip-section.md
      - Lab Solutions:
        - 'Solution - Lab: Skip Cells': modules/notebook-to-pipeline/exclude/lab-skip-cells-solution.md

